### ISSUE TITLE
Bug: in moss stitch row 1 starts in the wrong place

### ISSUE THREAD

**Issue by alenia** [alenia/planned-pooling#49]
<img width="493" alt="image" src="https://github.com/alenia/planned-pooling/assets/699890/81d8d806-ba42-451d-970a-a3ebbdfd8583">

The first row starts with a ch1 space not a sc

**Comment by alenia** [comment]
<img width="529" alt="image" src="https://github.com/alenia/planned-pooling/assets/699890/baad72ba-438b-4a68-874b-4220104502cd">

**Comment by alenia** [comment]
https://github.com/alenia/planned-pooling/blob/c5073dc073e5b893413da2d3f6b70e2989253aca/src/Swatch.scss#L18-L25
For every type of swatch, the direction is changed using flex-direction

https://github.com/alenia/planned-pooling/blob/c5073dc073e5b893413da2d3f6b70e2989253aca/src/Swatch.scss#L147-L149
For the moss stitch, the lines are staggered by putting horizontal margin on every other row.

If the margin is negative, it just keeps going the same way, it doesn’t change the stagger.

**Comment by joanwolk** [comment]
Is this what the correct view should look like?
<img width="484" alt="Screenshot 2024-03-02 at 11 39 03 AM" src="https://github.com/alenia/planned-pooling/assets/284712/b3cf8b14-5826-4e13-a6c8-6eef750bfe38">
