### ISSUE TITLE
Clicking slightly below the color slider (but still in the color popup box) closes the color picker

### ISSUE THREAD

**Issue by alenia** [alenia/planned-pooling#51]
On an ipad, when I try choosing colors and I tap somewhat too low (abvoe the labels, below the slider) the box closes. I think the box should only close/lose focus when you tap outside of it.

**Comment by alenia** [comment]
@joanwolk Do you know if this is hard? If it’s an easy fix I want it soon, and if it’s hard for react-color reasons I think we just work around this with default colors? it’s kinda janky though

**Comment by alenia** [comment]
Added soonish, it’s mvp if it’s a quick fix but if it’s fighting with the library then it’s not a release blocker

**Comment by joanwolk** [comment]
I don't know why that's happening so I don't know if it's a quick fix.

**Comment by alenia** [comment]
It looks like the cover has the onclick to hide the picker display, and the cover takes up the whole screen which includes the area in the popover (especially the areas that are just padding)

**Comment by alenia** [comment]
I'll take a look at this when I do #44

**Comment by joanwolk** [comment]
The picker should be on a higher z-index than the cover, I think, through
being rendered after the cover? Clicking in the padding of the picker is
no-op in desktop, but I can imagine the less precise nature of the iPad
makes it easy for part of the tap to register on the cover instead.
Rendering differences between desktop and iPad are also possible, I suppose.

**Comment by alenia** [comment]
I was having the same behavior on my desktop I’ll send a video laterSent from my iPhoneOn Mar 2, 2024, at 11:05 PM, Joan Wolkerstorfer ***@***.***> wrote:﻿
The picker should be on a higher z-index than the cover, I think, through

being rendered after the cover? Clicking in the padding of the picker is

no-op in desktop, but I can imagine the less precise nature of the iPad

makes it easy for part of the tap to register on the cover instead.

Rendering differences between desktop and iPad are also possible, I suppose.
