### ISSUE TITLE
Explain what color shift is better

### ISSUE THREAD

**Issue by alenia** [alenia/planned-pooling#52]
Mom still doesn’t understand it
There’s other issues about making it make sense
Could be copy or usability or design change

**Comment by joanwolk** [comment]
See also issue #31

**Comment by joanwolk** [comment]
I worked on the explanatory text for color shift tooltips while working on #44 

Tip details for negative shift values:
<img width="364" alt="Screenshot 2024-03-11 at 5 00 14 PM" src="https://github.com/alenia/planned-pooling/assets/284712/b43bae28-4154-4d8f-a546-9b5d43a346ab">

Tip is base message only for values `0 <= colorShift < seqLength`
<img width="365" alt="Screenshot 2024-03-11 at 5 00 27 PM" src="https://github.com/alenia/planned-pooling/assets/284712/cb587bb4-6f89-463d-90c9-a0fdbc5fcb26">

<img width="352" alt="Screenshot 2024-03-11 at 5 00 56 PM" src="https://github.com/alenia/planned-pooling/assets/284712/6db93d0c-a6e1-477f-8c00-e67273710c92">


Tip details for shift values equal to or greater than the length of the color sequence:
<img width="354" alt="Screenshot 2024-03-11 at 5 01 17 PM" src="https://github.com/alenia/planned-pooling/assets/284712/f387100d-8c27-4eea-b191-98ebc7bfc80f">
