### ISSUE TITLE
Colorpicker doesn't allow dragging

### ISSUE THREAD

**Issue by alenia** [alenia/planned-pooling#58]
Looking at the behavior of SketchPicker on https://casesandberg.github.io/react-color/ I can drag around or slide my slider before the complete event fires. This is how I expect a color picker to work. For some reason, there's no dragging on the color picker in our app right now.

**Comment by alenia** [comment]
https://github.com/alenia/planned-pooling/assets/699890/d8e0415b-7619-4032-8fc4-952a479cddcd

https://github.com/alenia/planned-pooling/assets/699890/18ea9efd-698a-4a38-b0b9-c693ff5bb62d

It seems to think that it is a text field perhaps?
The same behavior happens for the color slider at the bottom

**Comment by alenia** [comment]
@joanwolk Letting you know about this one

**Comment by joanwolk** [comment]
I used the `onChangeComplete` handler but you can switch it to `onChange`
if you prefer
